### ISSUE TITLE
StationXML output needs to generate a start year for the network.

### ISSUE THREAD

**Issue by rcasey-iris** [iris-edu/stationxml-seed-converter#2]
Dataless SEED does not have the notion of network years, so the converter needs to generate a start year for the network in StationXML, using the earliest epoch year found for that network's list of stations.

**Comment by timronan** [comment]
We still are not sure how to convert network start time from dataless to station xml. The new converter has been designed as a general converter between dataless and station xml, it is not specific to IRIS's data holdings so the network list may not work well with this project. One idea is to force the loader to assign start times to the convertered XML files. This issue is not resolved and needs further thinking. Please repost this issue on the new [seed-xml-converter](https://github.com/iris-edu/seed-xml-converter) github page.

**Comment by timronan** [comment]
The converter will create invalid stationXML and leave network epochs empty. Station operators will have to complete the stationXML documents by manually adding network epochs after the conversion process is complete. This method prevents the converter from automatically creating inaccurate network epochs within converted stationXML documents.
