### ISSUE TITLE
Convert an mseed data to Xml file

### ISSUE THREAD

**Issue by Jithinpm** [iris-edu/stationxml-seed-converter#60]
How can we convert a mseed data to xml file 1?

**Comment by timronan** [comment]
@Jithinpm stationxml files contain metadata information while mseed file contain time series information. Although these are complementary data types, there is no conversion between the two, because they are fundamentally different data. 

This software package does conversions between dataless seed and stationxml, which are both metadata. If you are interested in metadata conversions, please refer to this project's help documentation. https://iris-edu.github.io/stationxml-seed-converter/
